# Generated by Django 4.1.7 on 2023-05-08 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_available', models.BooleanField(default=True)),
                ('availability_changed_at', models.DateTimeField(auto_now_add=True)),
                ('last_content_change_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_available', models.BooleanField(default=True)),
                ('availability_changed_at', models.DateTimeField(auto_now_add=True)),
                ('last_content_change_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subfolders', to='mainpage.folder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_line_number', models.PositiveIntegerField()),
                ('end_line_number', models.PositiveIntegerField()),
                ('start_char_number', models.PositiveIntegerField(blank=True, null=True)),
                ('end_char_number', models.PositiveIntegerField(blank=True, null=True)),
                ('section_type', models.CharField(choices=[('PR', 'Procedure'), ('CO', 'Comment'), ('CD', 'Compiler directive'), ('VD', 'Variable declaration'), ('IA', 'Inline assembly')], max_length=2)),
                ('status', models.CharField(choices=[('C', 'Correct'), ('W', 'Warning'), ('E', 'Error')], max_length=1)),
                ('status_data', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('origin_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.file')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='parent_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subfiles', to='mainpage.folder'),
        ),
    ]
